version: '2'
services:
    chatbotunitext-app:
        image: chatbotunitext
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://chatbotunitext-mysql:3306/chatbotunitext?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    chatbotunitext-mysql:
        extends:
            file: mysql.yml
            service: chatbotunitext-mysql
